package net.trollyloki.hypixelapiwrapper.enums.pit;

public enum PitStat {
	LEFT_CLICKS, JOINS, GAPPLE_EATEN, ENDERCHEST_OPENED, FISHING_ROD_LAUNCHED, BLOCKS_PLACED, MELEE_DAMAGE_DEALT,
	CASH_EARNED, LAUNCHED_BY_LAUNCHERS, ARROWS_FIRED, ENCHANTED_TIER2, PLAYTIME_MINUTES, ENCHANTED_TIER1, CHAT_MESSAGES,
	BOW_DAMAGE_RECEIVED, ENCHANTED_TIER3, KILLS, DIAMOND_ITEMS_PURCHASED, DEATHS, SOUPS_DRANK, BLOCKS_BROKEN,
	GHEAD_EATEN, SWORD_HITS, CONTRACTS_COMPLETED, BOW_DAMAGE_DEALT, CONTRACTS_STARTED, DAMAGE_RECEIVED, JUMPED_INTO_PIT,
	MELEE_DAMAGE_RECEIVED, ARROW_HITS, DAMAGE_DEALT, ASSISTS, LAVA_BUCKET_EMPTIED, MAX_STREAK, WHEAT_FARMED,
	GOLD_FROM_FARMING, SEWER_TREASURES_FOUND, NIGHT_QUESTS_COMPLETED, DARK_PANTS_CRATED, FISHED_ANYTHING, FISHES_FISHED,
	KING_QUEST_COMPLETION, DARK_PANTS_T2, GOLD_FROM_SELLING_FISH, LAUNCHED_BY_DEMON_SPAWN, LAUNCHED_BY_ANGEL_SPAWN,
	INGOTS_CASH, INGOTS_PICKED_UP, RAGE_POTATOES_EATEN, OBSIDIAN_BROKEN, ENDLESS_QUIVER_ARROWS, EXTRA_FROM_TRICKLE_DOWN,
	LUCKY_DIAMOND_PIECES, RAMBO_KILLS, BOUNTIES_OF_500G_WITH_BH, VAMPIRE_HEALED_HP, HIDDEN_JEWEL_TRIGGERS;
}
